/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppCarimbarRouteImport } from './routes/_app/carimbar'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppCuponsRouteImport } from './routes/_app/cupons'
import { Route as AppPainelRouteImport } from './routes/_app/painel'
import { Route as AppProgramaRouteImport } from './routes/_app/programa'
import { Route as AppValidarRouteImport } from './routes/_app/validar'
import { Route as AuthCadastrarRouteImport } from './routes/auth/cadastrar'
import { Route as AuthEntrarRouteImport } from './routes/auth/entrar'
import { Route as CTokenRouteImport } from './routes/c.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCarimbarRoute = AppCarimbarRouteImport.update({
  id: '/carimbar',
  path: '/carimbar',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppCuponsRoute = AppCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AppRoute,
} as any)
const AppPainelRoute = AppPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramaRoute = AppProgramaRouteImport.update({
  id: '/programa',
  path: '/programa',
  getParentRoute: () => AppRoute,
} as any)
const AppValidarRoute = AppValidarRouteImport.update({
  id: '/validar',
  path: '/validar',
  getParentRoute: () => AppRoute,
} as any)
const AuthCadastrarRoute = AuthCadastrarRouteImport.update({
  id: '/auth/cadastrar',
  path: '/auth/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEntrarRoute = AuthEntrarRouteImport.update({
  id: '/auth/entrar',
  path: '/auth/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/carimbar': typeof AppCarimbarRoute
  '/clientes': typeof AppClientesRoute
  '/cupons': typeof AppCuponsRoute
  '/painel': typeof AppPainelRoute
  '/programa': typeof AppProgramaRoute
  '/validar': typeof AppValidarRoute
  '/auth/cadastrar': typeof AuthCadastrarRoute
  '/auth/entrar': typeof AuthEntrarRoute
  '/c/$token': typeof CTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/carimbar': typeof AppCarimbarRoute
  '/clientes': typeof AppClientesRoute
  '/cupons': typeof AppCuponsRoute
  '/painel': typeof AppPainelRoute
  '/programa': typeof AppProgramaRoute
  '/validar': typeof AppValidarRoute
  '/auth/cadastrar': typeof AuthCadastrarRoute
  '/auth/entrar': typeof AuthEntrarRoute
  '/c/$token': typeof CTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/carimbar': typeof AppCarimbarRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/cupons': typeof AppCuponsRoute
  '/_app/painel': typeof AppPainelRoute
  '/_app/programa': typeof AppProgramaRoute
  '/_app/validar': typeof AppValidarRoute
  '/auth/cadastrar': typeof AuthCadastrarRoute
  '/auth/entrar': typeof AuthEntrarRoute
  '/c/$token': typeof CTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/carimbar'
    | '/clientes'
    | '/cupons'
    | '/painel'
    | '/programa'
    | '/validar'
    | '/auth/cadastrar'
    | '/auth/entrar'
    | '/c/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/carimbar'
    | '/clientes'
    | '/cupons'
    | '/painel'
    | '/programa'
    | '/validar'
    | '/auth/cadastrar'
    | '/auth/entrar'
    | '/c/$token'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/_app/carimbar'
    | '/_app/clientes'
    | '/_app/cupons'
    | '/_app/painel'
    | '/_app/programa'
    | '/_app/validar'
    | '/auth/cadastrar'
    | '/auth/entrar'
    | '/c/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  AuthCadastrarRoute: typeof AuthCadastrarRoute
  AuthEntrarRoute: typeof AuthEntrarRoute
  CTokenRoute: typeof CTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/carimbar': {
      id: '/_app/carimbar'
      path: '/carimbar'
      fullPath: '/carimbar'
      preLoaderRoute: typeof AppCarimbarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cupons': {
      id: '/_app/cupons'
      path: '/cupons'
      fullPath: '/cupons'
      preLoaderRoute: typeof AppCuponsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/painel': {
      id: '/_app/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AppPainelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programa': {
      id: '/_app/programa'
      path: '/programa'
      fullPath: '/programa'
      preLoaderRoute: typeof AppProgramaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/validar': {
      id: '/_app/validar'
      path: '/validar'
      fullPath: '/validar'
      preLoaderRoute: typeof AppValidarRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/cadastrar': {
      id: '/auth/cadastrar'
      path: '/auth/cadastrar'
      fullPath: '/auth/cadastrar'
      preLoaderRoute: typeof AuthCadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/entrar': {
      id: '/auth/entrar'
      path: '/auth/entrar'
      fullPath: '/auth/entrar'
      preLoaderRoute: typeof AuthEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCarimbarRoute: typeof AppCarimbarRoute
  AppClientesRoute: typeof AppClientesRoute
  AppCuponsRoute: typeof AppCuponsRoute
  AppPainelRoute: typeof AppPainelRoute
  AppProgramaRoute: typeof AppProgramaRoute
  AppValidarRoute: typeof AppValidarRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCarimbarRoute: AppCarimbarRoute,
  AppClientesRoute: AppClientesRoute,
  AppCuponsRoute: AppCuponsRoute,
  AppPainelRoute: AppPainelRoute,
  AppProgramaRoute: AppProgramaRoute,
  AppValidarRoute: AppValidarRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  AuthCadastrarRoute: AuthCadastrarRoute,
  AuthEntrarRoute: AuthEntrarRoute,
  CTokenRoute: CTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
